"""Backward-compatible facade for TEM external-validation candidate registry."""

from .tem_external_validation_candidate_registry_engine import (
    ANNOTATION_PILOT,
    CASE_ID,
    CROSS_MATERIAL,
    CROSS_PHASE,
    EXCLUDED_REPRESENTATION,
    IN_DOMAIN_READY,
    INVENTORY_COLUMNS,
    METADATA_RESOLUTION,
    PROCESSED_IN_DOMAIN,
    RESULT,
    SCHEMA_VERSION,
    TARGET_SOURCE,
    WRONG_MODALITY,
    Candidate,
    CandidateContractError,
    RegistryConfig,
    load_registry_config,
    run_candidate_registry,
)

__all__ = [
    "ANNOTATION_PILOT",
    "CASE_ID",
    "CROSS_MATERIAL",
    "CROSS_PHASE",
    "EXCLUDED_REPRESENTATION",
    "IN_DOMAIN_READY",
    "INVENTORY_COLUMNS",
    "METADATA_RESOLUTION",
    "PROCESSED_IN_DOMAIN",
    "RESULT",
    "SCHEMA_VERSION",
    "TARGET_SOURCE",
    "WRONG_MODALITY",
    "Candidate",
    "CandidateContractError",
    "RegistryConfig",
    "load_registry_config",
    "run_candidate_registry",
]
