"""Audit public source HRTEM image arrays against source-predicted mask arrays.

The audit preserves source values and records source-asserted structural pairing.
It does not independently validate segmentation correctness, infer synthesis
conditions, apply pixel calibration, or compute physical dimensions.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import re
import shutil
import stat
import tempfile
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

import h5py
import numpy as np

from . import __version__

PUBLIC_CASE_ID = "public_cobalt_oxide_tem_source_image_mask_pairing"
PUBLIC_DOI = "10.5281/zenodo.14927582"
PUBLIC_DATASET_VERSION = "v1"
PUBLIC_LICENSE = "CC-BY-4.0"
PUBLIC_IMAGE_ARCHIVE_NAME = "TEM_images.zip"
PUBLIC_IMAGE_ARCHIVE_MD5 = "d1e991346d07b8a112c4b6dbfd8367ba"
PUBLIC_IMAGE_ARCHIVE_SHA256 = "a9e4618f697205bf8560ab14bc5e313d4011b51aaa6dbf8a5c62ddc22bc558d8"
PUBLIC_MASK_ARCHIVE_NAME = "Segmented_images.zip"
PUBLIC_MASK_ARCHIVE_MD5 = "63edc9b44264f8a1397bff806d58eade"
PUBLIC_MASK_ARCHIVE_SHA256 = "bd7816f3cf2869e4a349fc04d3e0d0464b3e14e9c8c8655f51e6e487fb59824b"
PUBLIC_PREFIXES = (
    "Co0_2",
    "Co0_4",
    "Co0_5",
    "Co0_7",
    "Co0_8",
    "DW0_6",
    "DW0_7",
    "DW0_43",
    "DW0_85",
    "DW1_0",
)

PAIRING_STATUS = "source_asserted_structurally_consistent_not_independently_verified"
LIMITATIONS = (
    "The Zenodo record describes corresponding segmentation results, and exact member prefixes, array shapes, and frame indices agree; this is source-asserted structural pairing rather than independent scientific verification.",
    "The selected source-image HDF5 arrays are numerically standardized per frame and do not preserve original detector intensity units.",
    "The selected HDF5 files do not contain per-file or per-frame pixel calibration attributes.",
    "The source-paper 86 pm context for 4k images is not automatically bound to every public HDF5 member and is not used for physical conversion.",
    "Opaque filename prefixes are preserved as identifiers and are not interpreted as synthesis conditions or composition values.",
    "The masks remain source-predicted outputs, not independent ground truth or predictions generated by this repository.",
    "No segmentation accuracy, particle identity, nanometre-scale size, phase, mechanism, causal, predictive, optimization, or engineering-release claim is supported.",
)


@dataclass(frozen=True)
class ArchiveSpec:
    """One exact externally hosted ZIP archive."""

    name: str
    url: str
    md5: str
    sha256: str
    expected_members: tuple[str, ...]


@dataclass(frozen=True)
class PairSpec:
    """One explicit source-image-member to mask-member identity mapping."""

    pair_id: str
    image_member: str
    mask_member: str


@dataclass(frozen=True)
class SourceImageMaskPairingConfig:
    """Strict contract for the public source-image and mask pairing audit."""

    case_id: str
    record_id: int
    doi: str
    dataset_version: str
    license: str
    source_description: str
    paper_doi: str
    paper_reported_four_k_pixel_size_pm: float
    calibration_binding_status: str
    image_archive: ArchiveSpec
    mask_archive: ArchiveSpec
    pairs: tuple[PairSpec, ...]
    image_dataset_name: str
    mask_dataset_name: str
    expected_shape: tuple[int, int, int]
    image_dtype: str
    mask_dtype: str
    image_mean_abs_tolerance: float
    image_std_abs_tolerance: float
    attributes_expected: bool

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "SourceImageMaskPairingConfig":
        _reject_unknown(
            payload,
            {
                "case_id",
                "source",
                "literature_context",
                "image_archive",
                "mask_archive",
                "pairs",
                "hdf5_contract",
            },
            "config",
        )
        source = _mapping(payload, "source")
        literature = _mapping(payload, "literature_context")
        image_archive = _archive_spec(_mapping(payload, "image_archive"), "image_archive")
        mask_archive = _archive_spec(_mapping(payload, "mask_archive"), "mask_archive")
        contract = _mapping(payload, "hdf5_contract")
        _reject_unknown(
            source,
            {"record_id", "doi", "dataset_version", "license", "source_description"},
            "source",
        )
        _reject_unknown(
            literature,
            {
                "paper_doi",
                "paper_reported_four_k_pixel_size_pm",
                "calibration_binding_status",
            },
            "literature_context",
        )
        _reject_unknown(
            contract,
            {
                "image_dataset_name",
                "mask_dataset_name",
                "expected_shape",
                "image_dtype",
                "mask_dtype",
                "image_mean_abs_tolerance",
                "image_std_abs_tolerance",
                "attributes_expected",
            },
            "hdf5_contract",
        )
        pair_entries = payload.get("pairs")
        if not isinstance(pair_entries, list) or not pair_entries:
            raise ValueError("pairs must be a non-empty list.")
        pairs: list[PairSpec] = []
        for index, pair_entry in enumerate(pair_entries):
            if not isinstance(pair_entry, Mapping):
                raise ValueError(f"pairs[{index}] must be an object.")
            _reject_unknown(pair_entry, {"pair_id", "image_member", "mask_member"}, f"pairs[{index}]")
            pairs.append(
                PairSpec(
                    pair_id=_required_text(pair_entry, "pair_id"),
                    image_member=_required_text(pair_entry, "image_member"),
                    mask_member=_required_text(pair_entry, "mask_member"),
                )
            )
        shape = contract.get("expected_shape")
        if not isinstance(shape, list):
            raise ValueError("expected_shape must be a list.")
        attributes_expected = contract.get("attributes_expected")
        if not isinstance(attributes_expected, bool):
            raise ValueError("attributes_expected must be a boolean.")
        config = cls(
            case_id=_required_text(payload, "case_id"),
            record_id=int(source["record_id"]),
            doi=_required_text(source, "doi"),
            dataset_version=_required_text(source, "dataset_version"),
            license=_required_text(source, "license"),
            source_description=_required_text(source, "source_description"),
            paper_doi=_required_text(literature, "paper_doi"),
            paper_reported_four_k_pixel_size_pm=float(
                literature["paper_reported_four_k_pixel_size_pm"]
            ),
            calibration_binding_status=_required_text(
                literature, "calibration_binding_status"
            ),
            image_archive=image_archive,
            mask_archive=mask_archive,
            pairs=tuple(pairs),
            image_dataset_name=_required_text(contract, "image_dataset_name"),
            mask_dataset_name=_required_text(contract, "mask_dataset_name"),
            expected_shape=tuple(int(value) for value in shape),
            image_dtype=_required_text(contract, "image_dtype"),
            mask_dtype=_required_text(contract, "mask_dtype"),
            image_mean_abs_tolerance=float(contract["image_mean_abs_tolerance"]),
            image_std_abs_tolerance=float(contract["image_std_abs_tolerance"]),
            attributes_expected=attributes_expected,
        )
        config.validate()
        return config

    def validate(self) -> None:
        if not re.fullmatch(r"[a-z0-9_]+", self.case_id):
            raise ValueError("case_id must use lowercase letters, digits, and underscores.")
        if len(self.expected_shape) != 3 or any(value <= 0 for value in self.expected_shape):
            raise ValueError("expected_shape must contain three positive integers.")
        if self.image_mean_abs_tolerance <= 0 or self.image_std_abs_tolerance <= 0:
            raise ValueError("image standardization tolerances must be positive.")
        if self.attributes_expected:
            raise ValueError("this audit supports only the pinned no-attribute HDF5 contract.")
        pair_ids = [pair.pair_id for pair in self.pairs]
        image_members = [pair.image_member for pair in self.pairs]
        mask_members = [pair.mask_member for pair in self.pairs]
        for label, values in (
            ("pair_id", pair_ids),
            ("image_member", image_members),
            ("mask_member", mask_members),
        ):
            if len(set(values)) != len(values):
                raise ValueError(f"{label} values must be unique.")
        for pair in self.pairs:
            _validate_member_name(pair.image_member)
            _validate_member_name(pair.mask_member)
        if set(image_members) != set(self.image_archive.expected_members):
            raise ValueError("source-image pair members do not equal image archive expected_members.")
        if set(mask_members) != set(self.mask_archive.expected_members):
            raise ValueError("mask pair members do not equal mask archive expected_members.")


def load_config(path: str | Path) -> SourceImageMaskPairingConfig:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("case config must contain a JSON object.")
    return SourceImageMaskPairingConfig.from_mapping(payload)


def validate_public_config(config: SourceImageMaskPairingConfig) -> None:
    expected_image_members = tuple(f"{prefix}_TEM_images.h5" for prefix in PUBLIC_PREFIXES)
    expected_mask_members = tuple(
        f"{prefix}_segmented_images.h5" for prefix in PUBLIC_PREFIXES
    )
    expected = {
        "case_id": PUBLIC_CASE_ID,
        "record_id": 14927582,
        "doi": PUBLIC_DOI,
        "dataset_version": PUBLIC_DATASET_VERSION,
        "license": PUBLIC_LICENSE,
        "paper_doi": "10.1021/acsnano.4c09312",
        "paper_reported_four_k_pixel_size_pm": 86.0,
        "calibration_binding_status": "paper_context_not_bound_to_individual_public_hdf5_members",
        "image_dataset_name": "images",
        "mask_dataset_name": "labels",
        "expected_shape": (5, 4096, 4096),
        "image_dtype": "float64",
        "mask_dtype": "float64",
        "image_mean_abs_tolerance": 1e-10,
        "image_std_abs_tolerance": 1e-12,
        "attributes_expected": False,
    }
    for field, value in expected.items():
        actual = getattr(config, field)
        if actual != value:
            raise ValueError(f"public config mismatch for {field}: {actual!r} != {value!r}")
    _validate_public_archive(
        config.image_archive,
        expected_name=PUBLIC_IMAGE_ARCHIVE_NAME,
        expected_md5=PUBLIC_IMAGE_ARCHIVE_MD5,
        expected_sha256=PUBLIC_IMAGE_ARCHIVE_SHA256,
        expected_members=expected_image_members,
        expected_url="https://zenodo.org/records/14927582/files/TEM_images.zip?download=1",
    )
    _validate_public_archive(
        config.mask_archive,
        expected_name=PUBLIC_MASK_ARCHIVE_NAME,
        expected_md5=PUBLIC_MASK_ARCHIVE_MD5,
        expected_sha256=PUBLIC_MASK_ARCHIVE_SHA256,
        expected_members=expected_mask_members,
        expected_url="https://zenodo.org/records/14927582/files/Segmented_images.zip?download=1",
    )
    expected_pairs = tuple(
        PairSpec(
            pair_id=prefix.lower(),
            image_member=f"{prefix}_TEM_images.h5",
            mask_member=f"{prefix}_segmented_images.h5",
        )
        for prefix in PUBLIC_PREFIXES
    )
    if config.pairs != expected_pairs:
        raise ValueError("public source-image/mask pair map does not match the audited contract.")


def run_pairing_audit(
    config: SourceImageMaskPairingConfig,
    output_dir: str | Path,
    *,
    image_archive_path: str | Path | None = None,
    mask_archive_path: str | Path | None = None,
) -> dict[str, Any]:
    output = _prepare_empty_output(output_dir)
    try:
        with tempfile.TemporaryDirectory(prefix="mca-tem-pair-") as temp_name:
            temp = Path(temp_name)
            image_archive, image_mode = _acquire_archive(
                config.image_archive, image_archive_path, temp
            )
            mask_archive, mask_mode = _acquire_archive(
                config.mask_archive, mask_archive_path, temp
            )
            image_hashes = _verify_archive(image_archive, config.image_archive)
            mask_hashes = _verify_archive(mask_archive, config.mask_archive)
            image_zip_inventory = _validate_zip_contract(
                image_archive, config.image_archive.expected_members
            )
            mask_zip_inventory = _validate_zip_contract(
                mask_archive, config.mask_archive.expected_members
            )
            file_rows: list[dict[str, Any]] = []
            frame_rows: list[dict[str, Any]] = []
            with zipfile.ZipFile(image_archive) as image_zip, zipfile.ZipFile(
                mask_archive
            ) as mask_zip:
                for index, pair in enumerate(config.pairs):
                    image_h5 = temp / f"image-{index}.h5"
                    mask_h5 = temp / f"mask-{index}.h5"
                    image_member_sha = _extract_member(image_zip, pair.image_member, image_h5)
                    mask_member_sha = _extract_member(mask_zip, pair.mask_member, mask_h5)
                    result = inspect_hdf5_pair(
                        image_h5,
                        mask_h5,
                        config=config,
                        pair=pair,
                        image_member_sha256=image_member_sha,
                        mask_member_sha256=mask_member_sha,
                    )
                    file_rows.append(result["file_row"])
                    frame_rows.extend(result["frame_rows"])
                    image_h5.unlink(missing_ok=True)
                    mask_h5.unlink(missing_ok=True)

        file_table = output / "tem_source_image_mask_file_pairs.csv"
        frame_table = output / "tem_source_image_mask_frame_pairs.csv"
        summary_path = output / "source_image_mask_pairing_summary.json"
        report_path = output / "source_image_mask_pairing_report.md"
        manifest_path = output / "source_image_mask_pairing_artifact_manifest.json"
        _write_csv(file_table, file_rows, FILE_COLUMNS)
        _write_csv(frame_table, frame_rows, FRAME_COLUMNS)
        summary = {
            "schema_version": "1.0",
            "case_id": config.case_id,
            "software_version": __version__,
            "source": {
                "repository": "Zenodo",
                "record_id": config.record_id,
                "doi": config.doi,
                "dataset_version": config.dataset_version,
                "license": config.license,
                "source_description": config.source_description,
                "image_archive": {
                    "name": config.image_archive.name,
                    "md5": image_hashes["md5"],
                    "sha256": image_hashes["sha256"],
                    "acquisition_mode": image_mode,
                },
                "mask_archive": {
                    "name": config.mask_archive.name,
                    "md5": mask_hashes["md5"],
                    "sha256": mask_hashes["sha256"],
                    "acquisition_mode": mask_mode,
                },
            },
            "literature_context": {
                "paper_doi": config.paper_doi,
                "paper_reported_four_k_pixel_size_pm": (
                    config.paper_reported_four_k_pixel_size_pm
                ),
                "calibration_binding_status": config.calibration_binding_status,
                "used_for_physical_conversion": False,
            },
            "hdf5_contract": {
                "image_dataset_name": config.image_dataset_name,
                "mask_dataset_name": config.mask_dataset_name,
                "shape_per_file": list(config.expected_shape),
                "image_dtype": config.image_dtype,
                "mask_dtype": config.mask_dtype,
                "image_mean_abs_tolerance": config.image_mean_abs_tolerance,
                "image_std_abs_tolerance": config.image_std_abs_tolerance,
                "attributes_present": False,
            },
            "result_counts": {
                "file_pair_count": len(file_rows),
                "frame_pair_count": len(frame_rows),
            },
            "source_image_representation": {
                "classification": "source_standardized_float64_image_array",
                "all_frame_means_near_zero": True,
                "all_frame_standard_deviations_near_one": True,
                "maximum_abs_frame_mean": max(
                    abs(float(row["image_mean"])) for row in frame_rows
                ),
                "maximum_abs_frame_std_deviation_from_one": max(
                    abs(float(row["image_std"]) - 1.0) for row in frame_rows
                ),
                "original_detector_intensity_available_in_selected_archive": False,
            },
            "pairing": {
                "status": PAIRING_STATUS,
                "source_asserted_correspondence": True,
                "exact_member_prefix_pairing": True,
                "equal_array_shapes": all(row["same_shape"] for row in file_rows),
                "equal_frame_counts": all(
                    row["same_frame_count"] for row in file_rows
                ),
                "same_frame_index_inventory": True,
                "independent_pairing_verification": False,
            },
            "processing": {
                "source_values_modified_by_repository": False,
                "source_image_preprocessing_performed_by_repository": False,
                "mask_resegmentation_performed": False,
                "model_training_performed": False,
                "model_inference_performed": False,
                "segmentation_accuracy_computed": False,
                "pixel_calibration_applied": False,
                "physical_size_computed": False,
                "filename_condition_semantics_interpreted": False,
            },
            "image_zip_inventory": {
                **image_zip_inventory,
                "data_member_crc_verified_during_stream_extraction": True,
            },
            "mask_zip_inventory": {
                **mask_zip_inventory,
                "data_member_crc_verified_during_stream_extraction": True,
            },
            "scientific_closeout": {
                "status": "Diagnostic",
                "result": PAIRING_STATUS,
                "strongest_evidence": (
                    "The exact checksum-bound Zenodo archives contain ten explicit "
                    "source-image/mask basename-prefix pairs with equal 5 x 4096 x 4096 arrays, "
                    "equal frame counts, numerically standardized source-image frames, and "
                    "per-member and per-frame content fingerprints."
                ),
                "primary_limitation": (
                    "The public files do not embed a signed mapping manifest or per-file "
                    "pixel calibration, and the masks are source predictions rather than "
                    "independent labels."
                ),
                "evidence_that_would_change_conclusion": (
                    "A source-provided immutable source-image-member/frame-to-mask-member/frame "
                    "manifest plus per-file calibration and independent validation labels."
                ),
                "suitable_for": [
                    "source-image/mask archive integrity validation",
                    "source-asserted structural pairing inventory",
                    "frame identity fingerprints",
                    "provenance-preserving software interoperability",
                ],
                "not_suitable_for": [
                    "segmentation accuracy",
                    "nanometre particle dimensions",
                    "particle identity confirmation",
                    "synthesis-condition comparison",
                    "causal inference",
                    "prediction or optimization",
                    "engineering release",
                ],
            },
            "limitations": list(LIMITATIONS),
        }
        _write_json(summary_path, summary)
        report_path.write_text(_build_report(summary), encoding="utf-8")
        manifest = _build_artifact_manifest(
            output,
            [file_table, frame_table, summary_path, report_path],
            case_id=config.case_id,
            image_archive_sha256=image_hashes["sha256"],
            mask_archive_sha256=mask_hashes["sha256"],
        )
        _write_json(manifest_path, manifest)
        return summary
    except Exception:
        if output.exists() and not any(output.iterdir()):
            output.rmdir()
        raise


def inspect_hdf5_pair(
    image_path: str | Path,
    mask_path: str | Path,
    *,
    config: SourceImageMaskPairingConfig,
    pair: PairSpec,
    image_member_sha256: str,
    mask_member_sha256: str,
) -> dict[str, Any]:
    image_path = Path(image_path)
    mask_path = Path(mask_path)
    frame_rows: list[dict[str, Any]] = []
    with h5py.File(image_path, "r") as image_h5, h5py.File(mask_path, "r") as mask_h5:
        _validate_hdf5_root(
            image_h5,
            member=pair.image_member,
            dataset_name=config.image_dataset_name,
            expected_shape=config.expected_shape,
            expected_dtype=config.image_dtype,
        )
        _validate_hdf5_root(
            mask_h5,
            member=pair.mask_member,
            dataset_name=config.mask_dataset_name,
            expected_shape=config.expected_shape,
            expected_dtype=config.mask_dtype,
        )
        image_dataset = image_h5[config.image_dataset_name]
        mask_dataset = mask_h5[config.mask_dataset_name]
        same_shape = tuple(image_dataset.shape) == tuple(mask_dataset.shape)
        same_frame_count = image_dataset.shape[0] == mask_dataset.shape[0]
        if not same_shape or not same_frame_count:
            raise ValueError(f"HDF5 pair shape mismatch for {pair.pair_id}.")
        for frame_index in range(image_dataset.shape[0]):
            image_fp = _frame_fingerprint(image_dataset, frame_index, require_binary=False)
            mask_fp = _frame_fingerprint(mask_dataset, frame_index, require_binary=True)
            if abs(float(image_fp["mean"])) > config.image_mean_abs_tolerance:
                raise ValueError(
                    f"source image frame mean drift for {pair.pair_id} frame {frame_index}: "
                    f"{image_fp['mean']}"
                )
            if abs(float(image_fp["std"]) - 1.0) > config.image_std_abs_tolerance:
                raise ValueError(
                    f"source image frame standard deviation drift for "
                    f"{pair.pair_id} frame {frame_index}: {image_fp['std']}"
                )
            frame_rows.append(
                {
                    "pair_id": pair.pair_id,
                    "frame_index": int(frame_index),
                    "image_member": pair.image_member,
                    "mask_member": pair.mask_member,
                    "image_frame_sha256": image_fp["sha256"],
                    "mask_frame_sha256": mask_fp["sha256"],
                    "height_px": int(image_dataset.shape[1]),
                    "width_px": int(image_dataset.shape[2]),
                    "image_min": image_fp["minimum"],
                    "image_max": image_fp["maximum"],
                    "image_mean": image_fp["mean"],
                    "image_std": image_fp["std"],
                    "mask_foreground_fraction": mask_fp["mean"],
                    "pairing_basis": (
                        "source_description_exact_prefix_equal_shape_same_frame_index"
                    ),
                    "pairing_status": PAIRING_STATUS,
                    "independent_pairing_verification": False,
                    "pixel_calibration_applied": False,
                }
            )
        file_row = {
            "pair_id": pair.pair_id,
            "image_member": pair.image_member,
            "mask_member": pair.mask_member,
            "image_member_sha256": image_member_sha256,
            "mask_member_sha256": mask_member_sha256,
            "image_dataset_name": config.image_dataset_name,
            "mask_dataset_name": config.mask_dataset_name,
            "shape": json.dumps(list(image_dataset.shape)),
            "image_dtype": str(image_dataset.dtype),
            "mask_dtype": str(mask_dataset.dtype),
            "frame_count": int(image_dataset.shape[0]),
            "same_shape": same_shape,
            "same_frame_count": same_frame_count,
            "attributes_present": False,
            "all_frames_numerically_standardized": True,
            "pairing_status": PAIRING_STATUS,
            "source_asserted_correspondence": True,
            "independent_pairing_verification": False,
            "pixel_calibration_available": False,
        }
    return {"file_row": file_row, "frame_rows": frame_rows}


def _validate_hdf5_root(
    handle: h5py.File,
    *,
    member: str,
    dataset_name: str,
    expected_shape: tuple[int, int, int],
    expected_dtype: str,
) -> None:
    if list(handle.keys()) != [dataset_name]:
        raise ValueError(
            f"{member} must contain only dataset {dataset_name!r}; "
            f"found {list(handle.keys())!r}."
        )
    if len(handle.attrs) != 0:
        raise ValueError(f"{member} root attributes changed from the pinned contract.")
    dataset = handle[dataset_name]
    if not isinstance(dataset, h5py.Dataset):
        raise ValueError(f"{member} {dataset_name!r} is not an HDF5 dataset.")
    if tuple(dataset.shape) != expected_shape:
        raise ValueError(
            f"{member} shape {tuple(dataset.shape)} != {expected_shape}."
        )
    if str(dataset.dtype) != expected_dtype:
        raise ValueError(f"{member} dtype {dataset.dtype} != {expected_dtype}.")
    if len(dataset.attrs) != 0:
        raise ValueError(f"{member} dataset attributes changed from the pinned contract.")


def _frame_fingerprint(
    dataset: h5py.Dataset,
    frame_index: int,
    *,
    require_binary: bool,
) -> dict[str, float | str]:
    digest = hashlib.sha256()
    minimum = math.inf
    maximum = -math.inf
    total = 0.0
    total_sq = 0.0
    count = 0
    height = int(dataset.shape[1])
    for start in range(0, height, 256):
        block = np.asarray(dataset[frame_index, start : start + 256, :])
        if not np.isfinite(block).all():
            raise ValueError(f"non-finite value in frame {frame_index}.")
        if require_binary:
            valid = np.logical_or(block == 0.0, block == 1.0)
            if not bool(valid.all()):
                bad = np.unique(block[~valid])[:10].tolist()
                raise ValueError(
                    f"non-binary mask value in frame {frame_index}: {bad}"
                )
        digest.update(np.ascontiguousarray(block).tobytes(order="C"))
        minimum = min(minimum, float(np.min(block)))
        maximum = max(maximum, float(np.max(block)))
        total += float(np.sum(block, dtype=np.float64))
        total_sq += float(
            np.sum(np.square(block, dtype=np.float64), dtype=np.float64)
        )
        count += int(block.size)
    mean = total / count
    variance = max(0.0, total_sq / count - mean * mean)
    return {
        "sha256": digest.hexdigest(),
        "minimum": minimum,
        "maximum": maximum,
        "mean": mean,
        "std": math.sqrt(variance),
    }


def _archive_spec(payload: Mapping[str, Any], context: str) -> ArchiveSpec:
    _reject_unknown(
        payload,
        {"name", "url", "md5", "sha256", "expected_members"},
        context,
    )
    return ArchiveSpec(
        name=_required_text(payload, "name"),
        url=_required_text(payload, "url"),
        md5=_digest(payload, "md5", 32),
        sha256=_digest(payload, "sha256", 64),
        expected_members=tuple(_text_list(payload, "expected_members")),
    )


def _validate_public_archive(
    archive: ArchiveSpec,
    *,
    expected_name: str,
    expected_md5: str,
    expected_sha256: str,
    expected_members: tuple[str, ...],
    expected_url: str,
) -> None:
    expected = {
        "name": expected_name,
        "url": expected_url,
        "md5": expected_md5,
        "sha256": expected_sha256,
        "expected_members": expected_members,
    }
    for field, value in expected.items():
        actual = getattr(archive, field)
        if actual != value:
            raise ValueError(
                f"public archive mismatch for {field}: {actual!r} != {value!r}"
            )


def _acquire_archive(
    spec: ArchiveSpec,
    supplied_path: str | Path | None,
    temporary: Path,
) -> tuple[Path, str]:
    destination = temporary / spec.name
    if supplied_path is None:
        _download(spec.url, destination)
        return destination, "downloaded_from_pinned_public_url"
    supplied = Path(supplied_path)
    if not supplied.is_file():
        raise FileNotFoundError(f"archive does not exist: {supplied}")
    if supplied.is_symlink():
        raise ValueError(f"archive path must not be a symlink: {supplied}")
    return supplied, "user_supplied_local_copy_verified_against_pinned_hashes"


def _verify_archive(path: Path, spec: ArchiveSpec) -> dict[str, str]:
    md5 = _hash_file(path, "md5")
    sha256 = _hash_file(path, "sha256")
    if md5 != spec.md5:
        raise ValueError(f"{spec.name} MD5 mismatch: {md5} != {spec.md5}")
    if sha256 != spec.sha256:
        raise ValueError(
            f"{spec.name} SHA-256 mismatch: {sha256} != {spec.sha256}"
        )
    return {"md5": md5, "sha256": sha256}


def _validate_zip_contract(
    archive: Path, expected_members: tuple[str, ...]
) -> dict[str, Any]:
    expected = set(expected_members)
    observed: set[str] = set()
    metadata: list[str] = []
    with zipfile.ZipFile(archive) as zf:
        for info in zf.infolist():
            _validate_zip_info(info)
            name = info.filename
            path = PurePosixPath(name)
            if name.startswith("__MACOSX/") or path.name.startswith("._"):
                metadata.append(name)
            elif not info.is_dir():
                observed.add(name)
        if observed != expected:
            raise ValueError(
                "archive members do not match pinned contract; "
                f"missing={sorted(expected-observed)}, "
                f"unexpected={sorted(observed-expected)}"
            )
    return {
        "data_members": sorted(observed),
        "metadata_members": sorted(metadata),
        "data_member_count": len(observed),
        "metadata_member_count": len(metadata),
        "safe_paths_verified": True,
        "symlinks_absent": True,
        "encrypted_entries_absent": True,
    }


def _validate_zip_info(info: zipfile.ZipInfo) -> None:
    name = info.filename
    normalized = name.replace("\\", "/")
    path = PurePosixPath(normalized)
    if name != normalized or path.is_absolute() or ".." in path.parts:
        raise ValueError(f"unsafe archive path: {name!r}")
    if any(part in ("", ".") for part in path.parts):
        raise ValueError(f"non-canonical archive path: {name!r}")
    mode = (info.external_attr >> 16) & 0xFFFF
    if stat.S_ISLNK(mode):
        raise ValueError(f"archive symlink rejected: {name!r}")
    if info.flag_bits & 0x1:
        raise ValueError(f"encrypted archive entry rejected: {name!r}")


def _extract_member(
    archive: zipfile.ZipFile, member: str, destination: Path
) -> str:
    digest = hashlib.sha256()
    with archive.open(member) as source, destination.open("wb") as target:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
            target.write(chunk)
    return digest.hexdigest()


def _download(url: str, destination: Path) -> None:
    request = urllib.request.Request(
        url, headers={"User-Agent": "materials-characterization-analyzer"}
    )
    with urllib.request.urlopen(request, timeout=180) as response, destination.open(
        "wb"
    ) as output:
        shutil.copyfileobj(response, output, length=1024 * 1024)


def _hash_file(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _prepare_empty_output(path: str | Path) -> Path:
    output = Path(path)
    if output.exists():
        if not output.is_dir():
            raise ValueError(f"output path is not a directory: {output}")
        if any(output.iterdir()):
            raise FileExistsError(
                f"output directory must be absent or empty: {output}"
            )
    else:
        output.mkdir(parents=True)
    return output


def _build_report(summary: Mapping[str, Any]) -> str:
    counts = summary["result_counts"]
    pairing = summary["pairing"]
    closeout = summary["scientific_closeout"]
    return "\n".join(
        [
            "# Public Cobalt Oxide TEM Source-Image–Mask Pairing Audit",
            "",
            f"- Dataset DOI: `{summary['source']['doi']}`",
            f"- File pairs: `{counts['file_pair_count']}`",
            f"- Frame pairs: `{counts['frame_pair_count']}`",
            f"- Pairing status: `{pairing['status']}`",
            "- Source-image representation: `numerically standardized float64 arrays`",
            "- Independent pairing verification: `false`",
            "- Pixel calibration applied: `false`",
            "- Physical size computed: `false`",
            "",
            "## Scientific closeout",
            "",
            f"**Evidence level: {closeout['status']}**",
            "",
            closeout["strongest_evidence"],
            "",
            f"Primary limitation: {closeout['primary_limitation']}",
            "",
            "The audit establishes a checksum-bound source-asserted structural pairing "
            "inventory. It does not validate segmentation accuracy or physical dimensions.",
            "",
        ]
    )


def _build_artifact_manifest(
    output: Path,
    files: Iterable[Path],
    *,
    case_id: str,
    image_archive_sha256: str,
    mask_archive_sha256: str,
) -> dict[str, Any]:
    records = []
    for path in sorted(files, key=lambda item: item.name):
        records.append(
            {
                "path": path.relative_to(output).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": _hash_file(path, "sha256"),
            }
        )
    return {
        "schema_version": "1.0",
        "case_id": case_id,
        "image_archive_sha256": image_archive_sha256,
        "mask_archive_sha256": mask_archive_sha256,
        "artifact_count": len(records),
        "artifacts": records,
    }


def _write_csv(
    path: Path,
    rows: Iterable[Mapping[str, Any]],
    columns: tuple[str, ...],
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=list(columns), extrasaction="raise"
        )
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column) for column in columns})


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _mapping(payload: Mapping[str, Any], field: str) -> Mapping[str, Any]:
    value = payload.get(field)
    if not isinstance(value, Mapping):
        raise ValueError(f"{field} must be an object.")
    return value


def _required_text(payload: Mapping[str, Any], field: str) -> str:
    value = payload.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field} must be a non-empty string.")
    return value.strip()


def _text_list(payload: Mapping[str, Any], field: str) -> list[str]:
    value = payload.get(field)
    if not isinstance(value, list) or not value:
        raise ValueError(f"{field} must be a non-empty list.")
    result: list[str] = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{field} entries must be non-empty strings.")
        _validate_member_name(item.strip())
        result.append(item.strip())
    return result


def _digest(payload: Mapping[str, Any], field: str, length: int) -> str:
    value = _required_text(payload, field).lower()
    if len(value) != length or any(
        character not in "0123456789abcdef" for character in value
    ):
        raise ValueError(
            f"{field} must be a {length}-character hexadecimal digest."
        )
    return value


def _validate_member_name(member: str) -> None:
    normalized = member.replace("\\", "/")
    path = PurePosixPath(normalized)
    if (
        member != normalized
        or path.is_absolute()
        or ".." in path.parts
        or len(path.parts) != 1
    ):
        raise ValueError(
            f"expected member must be a safe root-level filename: {member!r}"
        )


def _reject_unknown(
    payload: Mapping[str, Any], allowed: set[str], context: str
) -> None:
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise ValueError(f"unknown {context} field(s): {', '.join(unknown)}")


FILE_COLUMNS = (
    "pair_id",
    "image_member",
    "mask_member",
    "image_member_sha256",
    "mask_member_sha256",
    "image_dataset_name",
    "mask_dataset_name",
    "shape",
    "image_dtype",
    "mask_dtype",
    "frame_count",
    "same_shape",
    "same_frame_count",
    "attributes_present",
    "all_frames_numerically_standardized",
    "pairing_status",
    "source_asserted_correspondence",
    "independent_pairing_verification",
    "pixel_calibration_available",
)

FRAME_COLUMNS = (
    "pair_id",
    "frame_index",
    "image_member",
    "mask_member",
    "image_frame_sha256",
    "mask_frame_sha256",
    "height_px",
    "width_px",
    "image_min",
    "image_max",
    "image_mean",
    "image_std",
    "mask_foreground_fraction",
    "pairing_basis",
    "pairing_status",
    "independent_pairing_verification",
    "pixel_calibration_applied",
)
