"""Import source-predicted binary TEM masks without re-segmentation or model training."""

from __future__ import annotations

import csv
import hashlib
import json
import re
import shutil
import stat
import tempfile
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

import cv2
import h5py
import numpy as np

from . import __version__
from .contracts import AnalysisResult, FeatureRecord, PreprocessingStep, write_analysis_manifest
from .provenance import preprocessing_fingerprint

PUBLIC_CASE_ID = "public_cobalt_oxide_tem_source_masks"
PUBLIC_DATASET_DOI = "10.5281/zenodo.14927582"
PUBLIC_ARCHIVE_NAME = "Segmented_images.zip"
PUBLIC_ARCHIVE_MD5 = "63edc9b44264f8a1397bff806d58eade"
PUBLIC_ARCHIVE_SHA256 = "bd7816f3cf2869e4a349fc04d3e0d0464b3e14e9c8c8655f51e6e487fb59824b"
PUBLIC_EXPECTED_MEMBERS = (
    "Co0_2_segmented_images.h5",
    "Co0_4_segmented_images.h5",
    "Co0_5_segmented_images.h5",
    "Co0_7_segmented_images.h5",
    "Co0_8_segmented_images.h5",
    "DW0_6_segmented_images.h5",
    "DW0_7_segmented_images.h5",
    "DW0_43_segmented_images.h5",
    "DW0_85_segmented_images.h5",
    "DW1_0_segmented_images.h5",
)

QUALITY_FLAG = "source_prediction_review_required"
MASK_METHOD = "source_predicted_binary_mask_connected_components_8_no_filter"
LIMITATIONS = (
    "The HDF5 masks are source-predicted segmentation outputs, not independent ground truth and not predictions generated by this repository.",
    "The selected archive does not contain paired raw TEM intensities, pixel-size metadata, synthesis-condition metadata, or validation labels inside the HDF5 files.",
    "Opaque source filename labels are preserved as identifiers; their physical or synthesis meanings are not inferred.",
    "Connected components describe the supplied binary masks and are not automatically validated individual particles.",
    "No nanometre-scale size, segmentation accuracy, phase, mechanism, process-response, causal, predictive, optimization, or engineering-release claim is supported.",
)


@dataclass(frozen=True)
class TemMaskCaseConfig:
    """Strict configuration for one source-mask archive contract."""

    case_id: str
    record_id: int
    doi: str
    dataset_version: str
    license: str
    archive_name: str
    archive_url: str
    archive_md5: str
    archive_sha256: str
    expected_members: tuple[str, ...]
    dataset_name: str
    expected_shape: tuple[int, int, int]
    expected_dtype: str
    allowed_values: tuple[float, ...]
    connectivity: int

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "TemMaskCaseConfig":
        _reject_unknown(payload, {"case_id", "source", "hdf5_contract", "analysis"}, "config")
        source = _mapping(payload, "source")
        contract = _mapping(payload, "hdf5_contract")
        analysis = _mapping(payload, "analysis")
        _reject_unknown(
            source,
            {
                "record_id",
                "doi",
                "dataset_version",
                "license",
                "archive_name",
                "archive_url",
                "archive_md5",
                "archive_sha256",
                "expected_members",
            },
            "source",
        )
        _reject_unknown(
            contract,
            {"dataset_name", "expected_shape", "expected_dtype", "allowed_values"},
            "hdf5_contract",
        )
        _reject_unknown(analysis, {"connectivity"}, "analysis")
        shape = contract.get("expected_shape")
        allowed = contract.get("allowed_values")
        if not isinstance(shape, list):
            raise ValueError("expected_shape must be a list.")
        if not isinstance(allowed, list):
            raise ValueError("allowed_values must be a list.")
        config = cls(
            case_id=_required_text(payload, "case_id"),
            record_id=int(source["record_id"]),
            doi=_required_text(source, "doi"),
            dataset_version=_required_text(source, "dataset_version"),
            license=_required_text(source, "license"),
            archive_name=_required_text(source, "archive_name"),
            archive_url=_required_text(source, "archive_url"),
            archive_md5=_digest(source, "archive_md5", 32),
            archive_sha256=_digest(source, "archive_sha256", 64),
            expected_members=tuple(_text_list(source, "expected_members")),
            dataset_name=_required_text(contract, "dataset_name"),
            expected_shape=tuple(int(value) for value in shape),
            expected_dtype=_required_text(contract, "expected_dtype"),
            allowed_values=tuple(float(value) for value in allowed),
            connectivity=int(analysis["connectivity"]),
        )
        config.validate()
        return config

    def validate(self) -> None:
        if not re.fullmatch(r"[a-z0-9_]+", self.case_id):
            raise ValueError("case_id must use lowercase letters, digits, and underscores.")
        if len(self.expected_members) == 0 or len(set(self.expected_members)) != len(
            self.expected_members
        ):
            raise ValueError("expected_members must be non-empty and unique.")
        for member in self.expected_members:
            _validate_member_name(member)
            if not member.endswith("_segmented_images.h5"):
                raise ValueError(f"unexpected source-mask member naming: {member}")
        if len(self.expected_shape) != 3 or any(value <= 0 for value in self.expected_shape):
            raise ValueError("expected_shape must contain three positive integers.")
        if self.expected_dtype != "float64":
            raise ValueError("the supported source-mask dtype contract is float64.")
        if self.allowed_values != (0.0, 1.0):
            raise ValueError("the supported source-mask value contract is exactly [0.0, 1.0].")
        if self.connectivity != 8:
            raise ValueError("the supported connected-component contract uses connectivity=8.")


def load_config(path: str | Path) -> TemMaskCaseConfig:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("case config must contain a JSON object.")
    return TemMaskCaseConfig.from_mapping(payload)


def validate_public_case_config(config: TemMaskCaseConfig) -> None:
    """Fail closed if the tracked public case drifts from the audited Zenodo file."""
    expected = {
        "case_id": PUBLIC_CASE_ID,
        "record_id": 14927582,
        "doi": PUBLIC_DATASET_DOI,
        "dataset_version": "v1",
        "license": "CC-BY-4.0",
        "archive_name": PUBLIC_ARCHIVE_NAME,
        "archive_md5": PUBLIC_ARCHIVE_MD5,
        "archive_sha256": PUBLIC_ARCHIVE_SHA256,
        "expected_members": PUBLIC_EXPECTED_MEMBERS,
        "dataset_name": "labels",
        "expected_shape": (5, 4096, 4096),
        "expected_dtype": "float64",
        "allowed_values": (0.0, 1.0),
        "connectivity": 8,
    }
    for field, value in expected.items():
        actual = getattr(config, field)
        if actual != value:
            raise ValueError(f"public case config mismatch for {field}: {actual!r} != {value!r}")
    if config.archive_url != (
        "https://zenodo.org/records/14927582/files/Segmented_images.zip?download=1"
    ):
        raise ValueError("public case archive_url does not match the pinned Zenodo file URL.")


def run_case(
    config: TemMaskCaseConfig,
    output_dir: str | Path,
    *,
    archive_path: str | Path | None = None,
) -> dict[str, Any]:
    """Run a value-preserving audit of source-predicted TEM masks."""
    output = _prepare_empty_output(output_dir)
    try:
        with tempfile.TemporaryDirectory(prefix="mca-tem-mask-") as temporary_name:
            temporary = Path(temporary_name)
            archive = temporary / config.archive_name
            if archive_path is None:
                _download(config.archive_url, archive)
                acquisition_mode = "downloaded_from_pinned_public_url"
            else:
                supplied = Path(archive_path)
                if not supplied.is_file():
                    raise FileNotFoundError(f"archive does not exist: {supplied}")
                shutil.copyfile(supplied, archive)
                acquisition_mode = "user_supplied_local_copy_verified_against_pinned_hashes"

            archive_hashes = _verify_archive_hashes(archive, config)
            zip_inventory = _validate_zip_contract(archive, config)
            all_mask_rows: list[dict[str, Any]] = []
            all_component_rows: list[dict[str, Any]] = []
            analyses: list[AnalysisResult] = []
            file_summaries: list[dict[str, Any]] = []

            with zipfile.ZipFile(archive) as zf:
                for member_index, member in enumerate(config.expected_members):
                    extracted = temporary / f"member-{member_index}.h5"
                    source_sha256 = _extract_member(zf, member, extracted)
                    result = analyze_hdf5_file(
                        extracted,
                        config=config,
                        archive_member=member,
                        source_sha256=source_sha256,
                    )
                    all_mask_rows.extend(result["mask_rows"])
                    all_component_rows.extend(result["component_rows"])
                    analyses.extend(result["analyses"])
                    file_summaries.append(result["file_summary"])
                    extracted.unlink(missing_ok=True)

        mask_table = output / "tem_source_mask_summary.csv"
        component_table = output / "tem_source_mask_components.csv"
        feature_table = output / "tem_source_mask_features_long.csv"
        analysis_manifest = output / "case_analysis_manifest.json"
        summary_path = output / "case_summary.json"
        report_path = output / "case_report.md"
        artifact_manifest_path = output / "case_artifact_manifest.json"

        _write_csv(mask_table, all_mask_rows, MASK_COLUMNS)
        _write_csv(component_table, all_component_rows, COMPONENT_COLUMNS)
        feature_rows = [feature.to_dict() for analysis in analyses for feature in analysis.features]
        _write_csv(feature_table, feature_rows, FEATURE_COLUMNS)
        write_analysis_manifest(analyses, analysis_manifest)

        foreground_pixels = sum(int(row["foreground_pixel_count"]) for row in all_mask_rows)
        component_count = len(all_component_rows)
        border_component_count = sum(bool(row["touches_border"]) for row in all_component_rows)
        summary = {
            "schema_version": "1.0",
            "case_id": config.case_id,
            "software_version": __version__,
            "source": {
                "repository": "Zenodo",
                "record_id": config.record_id,
                "doi": config.doi,
                "dataset_version": config.dataset_version,
                "license": config.license,
                "archive_name": config.archive_name,
                "archive_md5": archive_hashes["md5"],
                "archive_sha256": archive_hashes["sha256"],
                "acquisition_mode": acquisition_mode,
            },
            "hdf5_contract": {
                "file_count": len(file_summaries),
                "dataset_name": config.dataset_name,
                "shape_per_file": list(config.expected_shape),
                "dtype": config.expected_dtype,
                "allowed_values": list(config.allowed_values),
                "full_array_binary_validation_performed": True,
                "source_attributes_present": False,
            },
            "result_counts": {
                "source_file_count": len(file_summaries),
                "mask_count": len(all_mask_rows),
                "analysis_count": len(analyses),
                "feature_record_count": len(feature_rows),
                "connected_component_count": component_count,
                "border_touching_component_count": border_component_count,
                "foreground_pixel_count": foreground_pixels,
            },
            "zip_inventory": zip_inventory,
            "file_summaries": file_summaries,
            "processing": {
                "source_values_modified": False,
                "resegmentation_performed": False,
                "component_filtering_performed": False,
                "pixel_calibration_applied": False,
                "physical_size_computed": False,
                "model_training_performed": False,
                "model_inference_performed": False,
                "segmentation_accuracy_computed": False,
                "synthesis_condition_inferred": False,
            },
            "scientific_closeout": {
                "status": "Diagnostic",
                "result": "source_predicted_tem_masks_imported_with_pixel_only_descriptors",
                "strongest_evidence": (
                    "Pinned CC-BY-4.0 Zenodo archive identity, full binary-value validation "
                    "for 50 source-predicted 4096x4096 masks, and per-file provenance."
                ),
                "primary_limitation": (
                    "The selected HDF5 files contain source predictions without paired raw "
                    "intensities, embedded pixel calibration, independent labels, or verified "
                    "synthesis-condition mapping."
                ),
                "suitable_for": [
                    "HDF5 import validation",
                    "source-mask integrity review",
                    "pixel-only descriptive connected-component diagnostics",
                    "provenance-preserving software interoperability",
                ],
                "not_suitable_for": [
                    "segmentation model validation",
                    "nanometre particle-size measurement",
                    "particle identity confirmation",
                    "shape-mechanism claims",
                    "synthesis-response modeling",
                    "causal inference",
                    "prediction or optimization",
                    "engineering release",
                ],
            },
            "limitations": list(LIMITATIONS),
        }
        _write_json(summary_path, summary)
        report_path.write_text(_build_report(summary), encoding="utf-8")
        artifact_manifest = _build_artifact_manifest(
            output,
            [
                mask_table,
                component_table,
                feature_table,
                analysis_manifest,
                summary_path,
                report_path,
            ],
            case_id=config.case_id,
            source_archive_sha256=archive_hashes["sha256"],
        )
        _write_json(artifact_manifest_path, artifact_manifest)
        return summary
    except Exception:
        if output.exists() and not any(output.iterdir()):
            output.rmdir()
        raise


def analyze_hdf5_file(
    path: str | Path,
    *,
    config: TemMaskCaseConfig,
    archive_member: str,
    source_sha256: str,
) -> dict[str, Any]:
    """Validate one HDF5 source file and compute pixel-only mask descriptors."""
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(path)
    sample_id = _sample_id_from_member(archive_member)
    mask_rows: list[dict[str, Any]] = []
    component_rows: list[dict[str, Any]] = []
    analyses: list[AnalysisResult] = []
    steps = (
        PreprocessingStep(
            step_id="source_mask_import",
            operation="read_source_predicted_hdf5_mask_without_value_modification",
            parameters={"dataset_name": config.dataset_name},
        ),
        PreprocessingStep(
            step_id="binary_validation",
            operation="validate_all_pixels_finite_and_exactly_binary",
            parameters={"allowed_values": list(config.allowed_values)},
        ),
        PreprocessingStep(
            step_id="connected_components",
            operation="connected_components_with_stats",
            parameters={"connectivity": config.connectivity, "filtering": "none"},
        ),
    )
    preprocessing_id = preprocessing_fingerprint("tem", steps)

    with h5py.File(path, "r") as handle:
        if list(handle.keys()) != [config.dataset_name]:
            raise ValueError(
                f"{archive_member} must contain only dataset {config.dataset_name!r}; "
                f"found {list(handle.keys())!r}."
            )
        if len(handle.attrs) != 0:
            raise ValueError(f"{archive_member} root attributes changed from the pinned contract.")
        dataset = handle[config.dataset_name]
        if not isinstance(dataset, h5py.Dataset):
            raise ValueError(f"{config.dataset_name!r} is not an HDF5 dataset.")
        if tuple(dataset.shape) != config.expected_shape:
            raise ValueError(
                f"{archive_member} shape {tuple(dataset.shape)} != {config.expected_shape}."
            )
        if str(dataset.dtype) != config.expected_dtype:
            raise ValueError(f"{archive_member} dtype {dataset.dtype} != {config.expected_dtype}.")
        if len(dataset.attrs) != 0:
            raise ValueError(
                f"{archive_member} dataset attributes changed from the pinned contract."
            )

        for frame_index in range(config.expected_shape[0]):
            raw = np.asarray(dataset[frame_index])
            if raw.shape != config.expected_shape[1:]:
                raise ValueError(f"unexpected frame shape in {archive_member}: {raw.shape}")
            if not np.isfinite(raw).all():
                raise ValueError(f"non-finite mask value in {archive_member} frame {frame_index}")
            valid = np.logical_or(raw == config.allowed_values[0], raw == config.allowed_values[1])
            if not bool(valid.all()):
                bad = np.unique(raw[~valid])[:10].tolist()
                raise ValueError(
                    f"non-binary mask value in {archive_member} frame {frame_index}: {bad}"
                )
            mask = raw.astype(np.uint8, copy=False)
            measurement_id = f"{sample_id}_mask_{frame_index:02d}"
            frame_summary, frame_components = summarize_binary_mask(
                mask,
                sample_id=sample_id,
                measurement_id=measurement_id,
                archive_member=archive_member,
                frame_index=frame_index,
                connectivity=config.connectivity,
            )
            mask_rows.append(frame_summary)
            component_rows.extend(frame_components)
            features = _features_from_summary(
                frame_summary,
                sample_id=sample_id,
                measurement_id=measurement_id,
                archive_member=archive_member,
                source_sha256=source_sha256,
                preprocessing_id=preprocessing_id,
                archive_name=config.archive_name,
            )
            analyses.append(
                AnalysisResult(
                    measurement_id=measurement_id,
                    sample_id=sample_id,
                    instrument="tem",
                    source_file=f"{config.archive_name}::{archive_member}",
                    source_sha256=source_sha256,
                    acquisition_metadata={
                        "dataset_doi": config.doi,
                        "dataset_version": config.dataset_version,
                        "source_archive": config.archive_name,
                        "source_archive_member": archive_member,
                        "source_dataset": config.dataset_name,
                        "source_frame_index": frame_index,
                        "source_shape": list(config.expected_shape),
                        "source_dtype": config.expected_dtype,
                        "source_label_semantics": "opaque_filename_label_not_interpreted",
                        "mask_provenance": "source_predicted_segmentation",
                        "raw_tem_pairing": "not_verified_in_selected_archive",
                        "pixel_calibration": "not_embedded_in_selected_hdf5",
                    },
                    preprocessing_steps=list(steps),
                    tables={
                        "mask_summary": "tem_source_mask_summary.csv",
                        "components": "tem_source_mask_components.csv",
                        "features": "tem_source_mask_features_long.csv",
                    },
                    features=features,
                    warnings=[
                        "source_prediction_not_independent_ground_truth",
                        "paired_raw_tem_image_not_verified",
                        "pixel_calibration_not_embedded",
                        "source_filename_label_meaning_not_inferred",
                    ],
                    limitations=list(LIMITATIONS),
                    software_version=__version__,
                )
            )

    return {
        "file_summary": {
            "archive_member": archive_member,
            "sample_id": sample_id,
            "source_sha256": source_sha256,
            "dataset_name": config.dataset_name,
            "shape": list(config.expected_shape),
            "dtype": config.expected_dtype,
            "mask_count": len(mask_rows),
            "component_count": sum(int(row["connected_component_count"]) for row in mask_rows),
            "full_array_binary_validation_performed": True,
            "source_attributes_present": False,
        },
        "mask_rows": mask_rows,
        "component_rows": component_rows,
        "analyses": analyses,
    }


def summarize_binary_mask(
    mask: np.ndarray,
    *,
    sample_id: str,
    measurement_id: str,
    archive_member: str,
    frame_index: int,
    connectivity: int = 8,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Compute transparent pixel-only descriptors for one already-binary mask."""
    if mask.ndim != 2 or mask.dtype != np.uint8:
        raise ValueError("mask must be a two-dimensional uint8 array.")
    unique = np.unique(mask)
    if not set(unique.tolist()).issubset({0, 1}):
        raise ValueError(f"mask values must be binary 0/1; found {unique.tolist()}")
    height, width = mask.shape
    total_pixels = int(mask.size)
    foreground_pixels = int(mask.sum(dtype=np.uint64))
    foreground_fraction = foreground_pixels / total_pixels
    label_count, labels, stats, centroids = cv2.connectedComponentsWithStats(
        mask,
        connectivity=connectivity,
        ltype=cv2.CV_32S,
    )
    component_count = int(label_count - 1)
    border_values = np.concatenate(
        [labels[0, :], labels[-1, :], labels[1:-1, 0], labels[1:-1, -1]]
    )
    border_labels = {int(value) for value in np.unique(border_values) if int(value) != 0}
    components: list[dict[str, Any]] = []
    for component_label in range(1, label_count):
        components.append(
            {
                "sample_id": sample_id,
                "measurement_id": measurement_id,
                "archive_member": archive_member,
                "frame_index": int(frame_index),
                "component_label": int(component_label),
                "area_pixels": int(stats[component_label, cv2.CC_STAT_AREA]),
                "bbox_x_px": int(stats[component_label, cv2.CC_STAT_LEFT]),
                "bbox_y_px": int(stats[component_label, cv2.CC_STAT_TOP]),
                "bbox_width_px": int(stats[component_label, cv2.CC_STAT_WIDTH]),
                "bbox_height_px": int(stats[component_label, cv2.CC_STAT_HEIGHT]),
                "centroid_x_px": float(centroids[component_label, 0]),
                "centroid_y_px": float(centroids[component_label, 1]),
                "touches_border": component_label in border_labels,
            }
        )
    areas = np.asarray([row["area_pixels"] for row in components], dtype=np.float64)
    area_sum = int(areas.sum()) if areas.size else 0
    if area_sum != foreground_pixels:
        raise RuntimeError(
            f"connected-component area {area_sum} != foreground pixels {foreground_pixels}"
        )
    summary = {
        "sample_id": sample_id,
        "measurement_id": measurement_id,
        "archive_member": archive_member,
        "frame_index": int(frame_index),
        "height_px": int(height),
        "width_px": int(width),
        "total_pixel_count": total_pixels,
        "foreground_pixel_count": foreground_pixels,
        "foreground_fraction": float(foreground_fraction),
        "connected_component_count": component_count,
        "border_touching_component_count": len(border_labels),
        "interior_component_count": component_count - len(border_labels),
        "component_area_pixels_min": float(areas.min()) if areas.size else None,
        "component_area_pixels_mean": float(areas.mean()) if areas.size else None,
        "component_area_pixels_median": float(np.median(areas)) if areas.size else None,
        "component_area_pixels_max": float(areas.max()) if areas.size else None,
        "component_area_pixels_total": area_sum,
        "connectivity": int(connectivity),
        "component_filtering": "none",
        "pixel_calibration_applied": False,
    }
    del labels
    return summary, components


def _features_from_summary(
    summary: Mapping[str, Any],
    *,
    sample_id: str,
    measurement_id: str,
    archive_member: str,
    source_sha256: str,
    preprocessing_id: str,
    archive_name: str,
) -> list[FeatureRecord]:
    specifications = (
        (
            "mask_foreground_fraction",
            "Foreground pixel fraction",
            "foreground_fraction",
            "fraction",
        ),
        (
            "mask_foreground_pixel_count",
            "Foreground pixel count",
            "foreground_pixel_count",
            "pixel",
        ),
        (
            "mask_connected_component_count",
            "Connected component count",
            "connected_component_count",
            "count",
        ),
        (
            "mask_border_touching_component_count",
            "Border-touching component count",
            "border_touching_component_count",
            "count",
        ),
        (
            "mask_interior_component_count",
            "Interior component count",
            "interior_component_count",
            "count",
        ),
        (
            "mask_component_area_pixels_mean",
            "Mean connected-component area",
            "component_area_pixels_mean",
            "pixel^2",
        ),
        (
            "mask_component_area_pixels_median",
            "Median connected-component area",
            "component_area_pixels_median",
            "pixel^2",
        ),
        (
            "mask_component_area_pixels_max",
            "Maximum connected-component area",
            "component_area_pixels_max",
            "pixel^2",
        ),
    )
    features: list[FeatureRecord] = []
    for feature_name, feature_label, key, unit in specifications:
        value = summary[key]
        if value is None:
            continue
        numeric = float(value) if isinstance(value, (float, np.floating)) else int(value)
        features.append(
            FeatureRecord(
                sample_id=sample_id,
                measurement_id=measurement_id,
                instrument="tem",
                feature_name=feature_name,
                feature_label=feature_label,
                value=numeric,
                unit=unit,
                method=MASK_METHOD,
                source_file=f"{archive_name}::{archive_member}",
                source_sha256=source_sha256,
                preprocessing_id=preprocessing_id,
                quality_flag=QUALITY_FLAG,
            )
        )
    return features


def _validate_zip_contract(archive: Path, config: TemMaskCaseConfig) -> dict[str, Any]:
    expected = set(config.expected_members)
    observed: set[str] = set()
    metadata_entries: list[str] = []
    max_ratio = 0.0
    with zipfile.ZipFile(archive) as zf:
        bad_crc_member = zf.testzip()
        if bad_crc_member is not None:
            raise ValueError(f"archive CRC validation failed for {bad_crc_member}.")
        for info in zf.infolist():
            _validate_zip_info(info)
            ratio = info.file_size / info.compress_size if info.compress_size else 0.0
            max_ratio = max(max_ratio, ratio)
            name = info.filename
            path = PurePosixPath(name)
            if name.startswith("__MACOSX/") or path.name.startswith("._"):
                metadata_entries.append(name)
                continue
            if info.is_dir():
                raise ValueError(f"unexpected directory entry: {name}")
            observed.add(name)
        if observed != expected:
            raise ValueError(
                "archive members do not match pinned contract; "
                f"missing={sorted(expected-observed)}, unexpected={sorted(observed-expected)}"
            )
    return {
        "valid_hdf5_members": sorted(observed),
        "macos_metadata_entries": sorted(metadata_entries),
        "valid_hdf5_member_count": len(observed),
        "macos_metadata_entry_count": len(metadata_entries),
        "crc_verified": True,
        "safe_paths_verified": True,
        "symlinks_absent": True,
        "encrypted_entries_absent": True,
        "max_entry_compression_ratio": max_ratio,
    }


def _validate_zip_info(info: zipfile.ZipInfo) -> None:
    name = info.filename
    normalized = name.replace("\\", "/")
    path = PurePosixPath(normalized)
    if name != normalized or path.is_absolute() or ".." in path.parts:
        raise ValueError(f"unsafe archive path: {name!r}")
    if any(part in ("", ".") for part in path.parts):
        raise ValueError(f"non-canonical archive path: {name!r}")
    unix_mode = (info.external_attr >> 16) & 0xFFFF
    if stat.S_ISLNK(unix_mode):
        raise ValueError(f"archive symlink rejected: {name!r}")
    if info.flag_bits & 0x1:
        raise ValueError(f"encrypted archive entry rejected: {name!r}")


def _extract_member(zf: zipfile.ZipFile, member: str, destination: Path) -> str:
    digest = hashlib.sha256()
    with zf.open(member) as source, destination.open("wb") as target:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
            target.write(chunk)
    return digest.hexdigest()


def _verify_archive_hashes(path: Path, config: TemMaskCaseConfig) -> dict[str, str]:
    md5 = _hash_file(path, "md5")
    sha256 = _hash_file(path, "sha256")
    if md5 != config.archive_md5:
        raise ValueError(f"archive MD5 mismatch: {md5} != {config.archive_md5}")
    if sha256 != config.archive_sha256:
        raise ValueError(f"archive SHA-256 mismatch: {sha256} != {config.archive_sha256}")
    return {"md5": md5, "sha256": sha256}


def _hash_file(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _download(url: str, destination: Path) -> None:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "materials-characterization-analyzer"},
    )
    with urllib.request.urlopen(request, timeout=120) as response, destination.open(
        "wb"
    ) as output:
        shutil.copyfileobj(response, output, length=1024 * 1024)


def _prepare_empty_output(path: str | Path) -> Path:
    output = Path(path)
    if output.exists():
        if not output.is_dir():
            raise ValueError(f"output path is not a directory: {output}")
        if any(output.iterdir()):
            raise FileExistsError(f"output directory must be absent or empty: {output}")
    else:
        output.mkdir(parents=True)
    return output


def _sample_id_from_member(member: str) -> str:
    stem = member.removesuffix("_segmented_images.h5")
    normalized = re.sub(r"[^a-z0-9]+", "_", stem.lower()).strip("_")
    return f"zenodo14927582_{normalized}"


def _write_csv(
    path: Path,
    rows: Iterable[Mapping[str, Any]],
    columns: tuple[str, ...],
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(columns), extrasaction="raise")
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column) for column in columns})


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _build_artifact_manifest(
    output: Path,
    files: Iterable[Path],
    *,
    case_id: str,
    source_archive_sha256: str,
) -> dict[str, Any]:
    records = []
    for path in sorted(files, key=lambda item: item.name):
        records.append(
            {
                "path": path.relative_to(output).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": _hash_file(path, "sha256"),
            }
        )
    return {
        "schema_version": "1.0",
        "case_id": case_id,
        "source_archive_sha256": source_archive_sha256,
        "artifact_count": len(records),
        "artifacts": records,
    }


def _build_report(summary: Mapping[str, Any]) -> str:
    counts = summary["result_counts"]
    closeout = summary["scientific_closeout"]
    return "\n".join(
        [
            "# Public Cobalt Oxide TEM Source-Mask Diagnostic Case",
            "",
            f"- Dataset DOI: `{summary['source']['doi']}`",
            f"- Source HDF5 files: `{counts['source_file_count']}`",
            f"- Source-predicted masks: `{counts['mask_count']}`",
            f"- Connected components: `{counts['connected_component_count']}`",
            "- Physical calibration applied: `false`",
            "- Model training or inference performed by this repository: `false`",
            "",
            "## Scientific closeout",
            "",
            f"**Evidence level: {closeout['status']}**",
            "",
            closeout["strongest_evidence"],
            "",
            f"Primary limitation: {closeout['primary_limitation']}",
            "",
            "The output supports source-mask integrity and pixel-only descriptive diagnostics. "
            "It does not validate segmentation accuracy or authorize nanometre-scale particle measurements.",
            "",
        ]
    )


def _mapping(payload: Mapping[str, Any], field: str) -> Mapping[str, Any]:
    value = payload.get(field)
    if not isinstance(value, Mapping):
        raise ValueError(f"{field} must be an object.")
    return value


def _required_text(payload: Mapping[str, Any], field: str) -> str:
    value = payload.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field} must be a non-empty string.")
    return value.strip()


def _text_list(payload: Mapping[str, Any], field: str) -> list[str]:
    value = payload.get(field)
    if not isinstance(value, list) or not value:
        raise ValueError(f"{field} must be a non-empty list.")
    result = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(f"{field} entries must be non-empty strings.")
        result.append(item.strip())
    return result


def _digest(payload: Mapping[str, Any], field: str, length: int) -> str:
    value = _required_text(payload, field).lower()
    if len(value) != length or any(
        character not in "0123456789abcdef" for character in value
    ):
        raise ValueError(f"{field} must be a {length}-character hexadecimal digest.")
    return value


def _validate_member_name(member: str) -> None:
    normalized = member.replace("\\", "/")
    path = PurePosixPath(normalized)
    if member != normalized or path.is_absolute() or ".." in path.parts or len(path.parts) != 1:
        raise ValueError(f"expected member must be a safe root-level filename: {member!r}")


def _reject_unknown(
    payload: Mapping[str, Any],
    allowed: set[str],
    context: str,
) -> None:
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise ValueError(f"unknown {context} field(s): {', '.join(unknown)}")


MASK_COLUMNS = (
    "sample_id",
    "measurement_id",
    "archive_member",
    "frame_index",
    "height_px",
    "width_px",
    "total_pixel_count",
    "foreground_pixel_count",
    "foreground_fraction",
    "connected_component_count",
    "border_touching_component_count",
    "interior_component_count",
    "component_area_pixels_min",
    "component_area_pixels_mean",
    "component_area_pixels_median",
    "component_area_pixels_max",
    "component_area_pixels_total",
    "connectivity",
    "component_filtering",
    "pixel_calibration_applied",
)
COMPONENT_COLUMNS = (
    "sample_id",
    "measurement_id",
    "archive_member",
    "frame_index",
    "component_label",
    "area_pixels",
    "bbox_x_px",
    "bbox_y_px",
    "bbox_width_px",
    "bbox_height_px",
    "centroid_x_px",
    "centroid_y_px",
    "touches_border",
)
FEATURE_COLUMNS = (
    "sample_id",
    "measurement_id",
    "instrument",
    "feature_name",
    "feature_label",
    "value",
    "unit",
    "method",
    "source_file",
    "source_sha256",
    "preprocessing_id",
    "quality_flag",
)
